{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0",
    "title": "To-do Demo",
    "description": "This OAS2 (Swagger 2) file represents a real API that lives at http://todos.stoplight.io.\n\nFor authentication information, click the apikey security scheme in the editor sidebar.",
    "contact": {
      "name": "Stoplight",
      "url": "https://stoplight.io"
    },
    "license": {
      "name": "MIT"
    }
  },
  "tags": [
    {
      "name": "Todos"
    }
  ],
  "servers": [
    {
      "url": "http://todos.stoplight.io"
    }
  ],
  "paths": {
    "/todos/{todoId}": {
      "parameters": [
        {
          "name": "todoId",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "tags": [
          "Todos"
        ],
        "summary": "Get Todo",
        "operationId": "GET_todo",
        "parameters": [
          {
            "name": "",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/todo-full"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": 1,
                      "name": "get food",
                      "completed": false,
                      "completed_at": "1955-04-23T13:22:52.685Z",
                      "created_at": "1994-11-05T03:26:51.471Z",
                      "updated_at": "1989-07-29T11:30:06.701Z"
                    }
                  }
                }
              },
              "/todos/foobar": {
                "examples": {
                  "example": {
                    "value": "{\n\t\"foo\": \"bar\"\n}\n"
                  }
                }
              },
              "/todos/chores": {
                "examples": {
                  "example": {
                    "value": {
                      "id": 9000,
                      "name": "Do Chores",
                      "completed": false,
                      "created_at": "2014-08-28T14:14:28.494Z",
                      "updated_at": "2014-08-28T14:14:28.494Z"
                    }
                  }
                }
              },
              "new": {
                "examples": {
                  "example": {
                    "value": {
                      "name": "esse qui proident labore",
                      "completed": null,
                      "id": 920778,
                      "completed_at": "2014-01-07T07:49:55.123Z",
                      "created_at": "1948-04-21T12:04:21.282Z",
                      "updated_at": "1951-12-19T11:10:34.039Z",
                      "user": {
                        "name": "irure deserunt fugiat",
                        "age": 121.45395681110494
                      },
                      "float": -47990796.228164576
                    }
                  }
                }
              }
            }
          },
          "404": {
            "$ref": "./todos.common.json#/components/responses/404"
          },
          "500": {
            "$ref": "./todos.common.json#/components/responses/500"
          }
        }
      },
      "put": {
        "tags": [
          "Todos"
        ],
        "summary": "Update Todo",
        "operationId": "PUT_todos",
        "security": [
          {
            "Basic": []
          },
          {
            "API Key": []
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/todo-partial",
                "example": {
                  "name": "my todo's new name",
                  "completed": false
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/todo-full"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": 9000,
                      "name": "It's Over 9000!!!",
                      "completed": true,
                      "completed_at": null,
                      "created_at": "2014-08-28T14:14:28.494Z",
                      "updated_at": "2015-08-28T14:14:28.494Z"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "./todos.common.json#/components/responses/401"
          },
          "404": {
            "$ref": "./todos.common.json#/components/responses/404"
          },
          "500": {
            "$ref": "./todos.common.json#/components/responses/500"
          }
        }
      },
      "delete": {
        "tags": [
          "Todos"
        ],
        "summary": "Delete Todo",
        "operationId": "DELETE_todo",
        "security": [
          {
            "Basic": []
          },
          {
            "API Key": []
          }
        ],
        "responses": {
          "204": {
            "description": ""
          },
          "401": {
            "$ref": "./todos.common.json#/components/responses/401"
          },
          "404": {
            "$ref": "./todos.common.json#/components/responses/404"
          },
          "500": {
            "$ref": "./todos.common.json#/components/responses/500"
          }
        }
      }
    },
    "/todos": {
      "get": {
        "tags": [
          "Todos"
        ],
        "summary": "List Todos",
        "description": "\u200b",
        "operationId": "GET_todos",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/todo-full"
                  }
                },
                "examples": {
                  "example": {
                    "value": [
                      {
                        "id": 1,
                        "name": "design the thingz",
                        "completed": true
                      },
                      {
                        "id": 2,
                        "name": "mock the thingz",
                        "completed": true
                      },
                      {
                        "id": 3,
                        "name": "code the thingz",
                        "completed": false
                      }
                    ]
                  }
                }
              },
              "empty": {
                "examples": {
                  "example": {
                    "value": []
                  }
                }
              }
            },
            "headers": {
              "foo": {
                "type": "string",
                "default": "bar"
              }
            }
          },
          "500": {
            "$ref": "./todos.common.json#/components/responses/500"
          }
        }
      },
      "post": {
        "tags": [
          "Todos"
        ],
        "summary": "Create Todo",
        "description": "This creates a Todo object.\n\nTesting `inline code`.",
        "operationId": "POST_todos",
        "security": [
          {
            "API Key": []
          },
          {
            "Basic": []
          }
        ],
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/todo-partial",
                "example": {
                  "name": "my todo's name",
                  "completed": false
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/todo-full"
                },
                "examples": {
                  "example": {
                    "value": {
                      "id": 9000,
                      "name": "It's Over 9000!!!",
                      "completed": null,
                      "completed_at": null,
                      "created_at": "2014-08-28T14:14:28.494Z",
                      "updated_at": "2014-08-28T14:14:28.494Z"
                    }
                  }
                }
              },
              "/todos/chores": {
                "examples": {
                  "example": {
                    "value": {
                      "id": 9000,
                      "name": "Do Chores",
                      "completed": false,
                      "created_at": "2014-08-28T14:14:28.494Z",
                      "updated_at": "2014-08-28T14:14:28.494Z"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "./todos.common.json#/components/responses/401"
          },
          "500": {
            "$ref": "./todos.common.json#/components/responses/500"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "todo-partial": {
        "$ref": "ref.json#/components/schemas/todo-partial"
      },
      "todo-full": {
        "title": "Todo Full",
        "allOf": [
          {
            "$ref": "#/components/schemas/todo-partial"
          },
          {
            "type": "object",
            "properties": {
              "id": {
                "type": "integer",
                "minimum": 0,
                "maximum": 1000000
              },
              "completed_at": {
                "type": [
                  "string",
                  "null"
                ],
                "format": "date-time"
              },
              "created_at": {
                "type": "string",
                "format": "date-time"
              },
              "updated_at": {
                "type": "string",
                "format": "date-time"
              },
              "user": {
                "$ref": "./todos.common.json#/components/schemas/user"
              }
            },
            "required": [
              "id",
              "user"
            ]
          }
        ]
      }
    },
    "parameters": {
      "limit": {
        "name": "limit",
        "in": "query",
        "description": "This is how it works.",
        "required": false,
        "schema": {
          "type": "integer",
          "maximum": 100
        }
      },
      "skip": {
        "name": "skip",
        "in": "query",
        "required": false,
        "schema": {
          "type": "string"
        }
      }
    },
    "securitySchemes": {
      "Basic": {
        "type": "basic"
      },
      "API Key": {
        "type": "apiKey",
        "name": "apikey",
        "in": "query"
      }
    }
  }
}
